{% set name = "dask-awkward" %}
{% set version = "2024.12.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/dask_awkward/dask_awkward-{{ version }}.tar.gz
  sha256: c178f4bb245593d44e22c9a6d7afc20703a9e08431689cf4b4da9e8c9384cdb0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling >=1.8.0
    - hatch-vcs
    - toml
  run:
    - python >={{ python_min }}
    - awkward >=2.5.1
    - dask >=2023.04.0
    - cachetools
    - typing_extensions >=4.8.0

test:
  imports:
    - dask_awkward

about:
  home: https://dask-awkward.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Connecting awkward-array and Dask.
  description: |
    dask-awkward provides a native Dask collection representing
    partitioned awkward arrays.
  doc_url: https://dask-awkward.readthedocs.io/
  dev_url: https://github.com/dask-contrib/dask-awkward/

extra:
  recipe-maintainers:
    - jpivarski
    - lgray
    - agoose77
    - douglasdavis
    - pfackeldey
    - martindurant
